### ISSUE TITLE
Getting error with componentInputData of DynamicComponent

### ISSUE THREAD

**Issue by ShahriarSayeed** [devyumao/angular2-busy#16]
I'm getting this error.

zone.js:355 Unhandled Promise rejection: Template parse errors:
Can't bind to 'componentInputData' since it isn't a known property of 'DynamicComponent'. ("erClass" *ngIf="isActive()" @flyInOut>
            <DynamicComponent [componentTemplate]="template" [ERROR ->][componentInputData]="context">
            </DynamicComponent>
        </div>"): 

@sielay fixed that problem in his commit https://github.com/devyumao/angular2-busy/pull/15/commits/6735557cd7a2e01c03b38c0896afb685fb99d69f

Plz merge this to avoid that problem to others.

**Comment by adonespitogo** [comment]
+1

**Comment by al-pt-old** [comment]
You must remove the dependencies "ts-metadata-helper" & "angular2-dynamic-component" from your package, because "angular2-dynamic-component": "1.0.5" is not compatible with "angular2-dynamic-component": "0.0.50" and they are already included as dependencies

{
"name": "angular2-busy",
...
},
"dependencies": {
"ts-metadata-helper": "0.0.3",
"angular2-dynamic-component": "0.0.50"
},

**Comment by AleksRojas** [comment]
I'm still getting this error...

Can't bind to 'componentInputData' since it isn't a known property of 'DynamicComponent'. ("erClass" *ngIf="isActive()" @flyInOut> <DynamicComponent [componentTemplate]="template" [ERROR ->][componentInputData]="context">

is there any plan to merge these changes?
