### ISSUE TITLE
Disable forms and buttons

### ISSUE THREAD

**Issue by radyz** [devyumao/angular2-busy#5]
Would it be out of scope to disable input buttons or forms within an element containing ngBusy? This would help prevent multiple form submissions while the observables or promises are being processed.

**Comment by devyumao** [comment]
Hi radyz,

Thank you for your suggestion. In my opinion, it is not quite proper for a loading plugin to modify the element's attributes. It only has rights to add the indicator thing into the element.

In order to achieve your aim, you could set a variable binding to the 'disable' attribute of the button, then disable it before a form submission, and enable it in the submission's resolve. That would be an appreciate method.
